### ISSUE TITLE
Create custom sign-in component that imports sign-in mixin

### ISSUE THREAD

**Issue by ekraihan** [CS450-ECE461/fall2017-team4-mobile#16]
Some code to do this
```javascript
$("*").removeClass((i, classes) => {
	return classes.split(' ')
		.filter(cssClass => cssClass.includes('mdl'))
		.join(' ');
});
```
^ Removes all css classes that include `mdl`
Or maybe
```javascript
$('link[rel="stylesheet"]').attr('disabled', 'disabled');
```
which removes all stylesheets

UPDATE:
After talking to Dr. Hill, we are going to import his mixin for sign-in into our own component so that it does not implement mdl elements.

**Comment by ekraihan** [comment]
Maybe find a way to remove the material dependency from Dr. Hill’s  add on?

**Comment by JerebChase** [comment]
I did research removing the dependency all day yesterday and couldn't find a way to do it. But that doesn't mean it's not possible. As to the the code above, would that go in the sign-in controller file? Sign-in is really the only place we will need to get rid of the mdl classes that are automatically inserted...

**Comment by ekraihan** [comment]
@JerebChase we also extend gatekeeper's `AuthenicatedRoute` which also has mdl :( . So we'll need to remove it from there too. I think I have a way to remove all material stuff, but I think its a pretty bad way, but we can talk

**Comment by JerebChase** [comment]
You're right, but at that point we are not forced to use any of the components that come with gatekeeper. We can use our own components that don't have mdl attributes... But, yes, we should talk ;)
