### ISSUE TITLE
Work out stuff with backend

### ISSUE THREAD

**Issue by ekraihan** [CS450-ECE461/fall2017-team4-mobile#60]
- [ ] Get responses into json api format (figure out which models to be lenient on) (they don't need to expect json api)
- [x] Rename conversation type to either "conversation" or "chat"
- [x] Get messaging to work
- [ ] Search???
- [ ] Dummy Data for lots of models

**Comment by bakerjoh000** [comment]
All of these things are extremely important before we present on Wednesday.
