### ISSUE TITLE
Set up Ember Models

### ISSUE THREAD

**Issue by ekraihan** [CS450-ECE461/fall2017-team4-mobile#7]
- [x] User
- [x] Profile
- [x] Occupation
- [x] Skill
- [x] Experience
- [x] Education

**Comment by JerebChase** [comment]
The basic models have been generated, but this will need to be revisited after we have gotten solid data from the designers and nailed down what our model is with the backend guys.

**Comment by ekraihan** [comment]
Closing because its kind of generic and it is constantly changing
